/**
 * A small Markdown renderer for the delivered document.
 *
 * Deliberately not a library: the delivery format is fixed and narrow (headings,
 * lists, bold, italic, code, rules), the content is generated by our own
 * assembler, and pulling in a parser plus a sanitiser for six constructs is a
 * poor trade. Everything renders as React elements, so nothing is ever injected
 * as raw HTML.
 */

import React from 'react';

export function Markdown({ source }: { source: string }): React.ReactElement {
  return <>{renderBlocks(source)}</>;
}

function renderBlocks(source: string): React.ReactNode[] {
  const lines = source.replace(/\r\n/g, '\n').split('\n');
  const out: React.ReactNode[] = [];
  let index = 0;
  let key = 0;

  while (index < lines.length) {
    const line = lines[index];

    if (!line.trim()) {
      index += 1;
      continue;
    }

    if (/^---+$/.test(line.trim())) {
      out.push(<hr key={key++} className="my-8 border-line" />);
      index += 1;
      continue;
    }

    const heading = line.match(/^(#{1,4})\s+(.*)$/);
    if (heading) {
      const level = heading[1].length;
      const text = inline(heading[2]);
      if (level === 1) {
        out.push(
          <h1 key={key++} className="font-display text-3xl sm:text-4xl font-semibold tracking-tight text-ink mb-5 balance">
            {text}
          </h1>,
        );
      } else if (level === 2) {
        out.push(
          <h2 key={key++} className="font-display text-xl sm:text-2xl font-semibold tracking-tight text-ink mt-10 mb-3 pt-6 border-t border-line first:mt-0 first:pt-0 first:border-0">
            {text}
          </h2>,
        );
      } else {
        out.push(
          <h3 key={key++} className="text-base font-semibold text-ink mt-6 mb-2">
            {text}
          </h3>,
        );
      }
      index += 1;
      continue;
    }

    if (/^>\s?/.test(line)) {
      const quote: string[] = [];
      while (index < lines.length && /^>\s?/.test(lines[index])) {
        quote.push(lines[index].replace(/^>\s?/, ''));
        index += 1;
      }
      out.push(
        <blockquote key={key++} className="border-l-2 border-accent pl-4 my-4 text-muted italic">
          {inline(quote.join(' '))}
        </blockquote>,
      );
      continue;
    }

    if (/^[-*]\s+/.test(line)) {
      const items: string[] = [];
      while (index < lines.length && /^[-*]\s+/.test(lines[index])) {
        items.push(lines[index].replace(/^[-*]\s+/, ''));
        index += 1;
      }
      out.push(
        <ul key={key++} className="my-3 space-y-2">
          {items.map((item, i) => (
            <li key={i} className="relative pl-5 text-[15px] leading-relaxed text-ink">
              <span aria-hidden className="absolute left-0 top-[0.62em] size-1.5 rounded-full bg-accent" />
              {inline(item)}
            </li>
          ))}
        </ul>,
      );
      continue;
    }

    if (/^\d+\.\s+/.test(line)) {
      const items: string[] = [];
      while (index < lines.length && /^\d+\.\s+/.test(lines[index])) {
        items.push(lines[index].replace(/^\d+\.\s+/, ''));
        index += 1;
      }
      out.push(
        <ol key={key++} className="my-3 space-y-2">
          {items.map((item, i) => (
            <li key={i} className="relative pl-8 text-[15px] leading-relaxed text-ink">
              <span
                aria-hidden
                className="absolute left-0 top-0 flex size-5 items-center justify-center rounded-full bg-accent-wash text-[11px] font-semibold tabular-nums text-accent"
              >
                {i + 1}
              </span>
              {inline(item)}
            </li>
          ))}
        </ol>,
      );
      continue;
    }

    const paragraph: string[] = [];
    while (index < lines.length && lines[index].trim() && !isBlockStart(lines[index])) {
      paragraph.push(lines[index]);
      index += 1;
    }
    out.push(
      <p key={key++} className="my-3 text-[15px] leading-relaxed text-ink">
        {inline(paragraph.join(' '))}
      </p>,
    );
  }

  return out;
}

function isBlockStart(line: string): boolean {
  return /^(#{1,4}\s|[-*]\s|\d+\.\s|>|---+$)/.test(line);
}

/** Bold, italic and inline code. Emitted as elements, never as HTML. */
function inline(text: string): React.ReactNode[] {
  const tokens = text.split(/(\*\*[^*]+\*\*|__[^_]+__|`[^`]+`|_[^_]+_|\*[^*]+\*)/g);
  return tokens.filter(Boolean).map((token, i) => {
    if (/^\*\*[\s\S]+\*\*$/.test(token) || /^__[\s\S]+__$/.test(token)) {
      return (
        <strong key={i} className="font-semibold text-ink">
          {token.slice(2, -2)}
        </strong>
      );
    }
    if (/^`[^`]+`$/.test(token)) {
      return (
        <code key={i} className="rounded bg-sunken px-1.5 py-0.5 font-mono text-[0.85em] text-ink">
          {token.slice(1, -1)}
        </code>
      );
    }
    if (/^_[^_]+_$/.test(token) || /^\*[^*]+\*$/.test(token)) {
      return (
        <em key={i} className="text-muted">
          {token.slice(1, -1)}
        </em>
      );
    }
    return <React.Fragment key={i}>{token}</React.Fragment>;
  });
}
